"""Supported environment-variable names."""

ENV_LLM_PROVIDER = "LLM_PROVIDER"
ENV_LLM_API_KEY = "LLM_API_KEY"
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"
ENV_LLM_BASE_URL = "LLM_BASE_URL"
ENV_LLM_MODEL = "LLM_MODEL"
ENV_LLM_TIMEOUT = "LLM_TIMEOUT"
ENV_LLM_COMPACTION_KEEP_RECENT_EXCHANGES = (
    "LLM_COMPACTION_KEEP_RECENT_EXCHANGES"
)
ENV_LLM_COMPACTION_MODEL = "LLM_COMPACTION_MODEL"
ENV_LLM_COMPACTION_AUTO_MAX_TOKENS = "LLM_COMPACTION_AUTO_MAX_TOKENS"
ENV_PLAIN_AGENT_ENABLE_NETWORK = "PLAIN_AGENT_ENABLE_NETWORK"

ENV_VARIABLE_NAMES = (
    ENV_LLM_PROVIDER,
    ENV_LLM_API_KEY,
    ENV_OPENAI_API_KEY,
    ENV_DEEPSEEK_API_KEY,
    ENV_LLM_BASE_URL,
    ENV_LLM_MODEL,
    ENV_LLM_TIMEOUT,
    ENV_LLM_COMPACTION_KEEP_RECENT_EXCHANGES,
    ENV_LLM_COMPACTION_MODEL,
    ENV_LLM_COMPACTION_AUTO_MAX_TOKENS,
    ENV_PLAIN_AGENT_ENABLE_NETWORK,
)
